### ISSUE TITLE
Azure IoT Edge Tools for VS 2019 - "Build IoT Edge Modules" command ignoring build args specified in module.json

### ISSUE THREAD

**Issue by BinaryMike** [microsoft/vs-azure-iot-edge-docs#25] opened 2020-03-26 01:57 UTC
I'm currently using the Azure IoT Edge Tools for VS 2019, and when I specify docker build args in the "buildOptions" section of the module.json, these build args are not being passed to the "docker build" command.  When I use the same deployment.template.json and module.json using the VS Code tools, it works fine.

Attached is a zip file of a sample project illustrating the problem.  If built in VS 2019, the RUN command checking the value of the build argument fails.  When run in VS Code, it succeeds.  You can also see that VS 2019 does not call "docker build" with the --build-arg parameter.

[SampleIoTEdgeApp.zip](https://github.com/microsoft/vs-azure-iot-edge-docs/files/4384590/SampleIoTEdgeApp.zip)

**Comment by SLdragon** [comment] 2020-03-26 07:20
Thanks for your feedback, and I will test it

**Comment by SLdragon** [comment] 2020-03-30 02:38
Hi, @BinaryMike, for current version of Visual Studio extension, it not support the BuildOptions now, we are planning to support it in the future release, and I will let you know the progress, thank you!

**Comment by konichi3** [comment] 2021-01-09 00:39
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:39 UTC
Labels: Obsolete
