### ISSUE TITLE
Cannot Add a FunctionsModule in VS2019

### ISSUE THREAD

**Issue by Fredborg** [microsoft/vs-azure-iot-edge-docs#9] opened 2019-09-24 06:36 UTC
Hi,

I cannot get a FunctionModule to work in an IotEdge Hub Dev project under Visual Studio 2019.

I tried the following:

We run command:
**dotnet new aziotedgefunction -n LogTransferModule**

This generates a new Azure Functions Module Project in the Solution Directory

If you then try and include the Project into the existing solution you get the following error:

_The following module cannot be added as a Module Reference because its not an IoT Edge module_

I edited the Project File, and I noticed, that every IOT Edge module has an ItemGroup called ProjectCapability, I added that ItemGroup to the newly generated project. Now I could successfully Add the module to the Solution.

But when I run the solution on IoT Edge Hub dev simulator, the modules starts up, then the Client crashes and every module gets removed from IoT Edge hub dev.
Why can’t I add an Azure FunctionsModule in VS2019?

It works fine if I add a Functions Project in Visual Studio Code, but I want to use Visual Studio for development and debugging.

Hope you can help.

**Comment by SLdragon** [comment] 2019-09-25 04:49
Thanks for your feedback, for the current version of visual studio, it only supports C/C# module, Functions Module is not supported now. We will discuss and investigate how to achieve this, and would let you know when it is ready.

**Comment by konichi3** [comment] 2021-01-09 00:38
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:38 UTC
Labels: Obsolete
